import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F6F9',
  },

  /** Header Gradient */
  header: {
    paddingVertical: 28,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 16,
  },

  /** Scroll content */
  contentContainer: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },

  /** Card sự kiện */
  eventCardWrapper: {
    marginBottom: 20,
  },
  card: {
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 8,
    position: 'relative',
    transform: [{scale: 1}],
  },

  eventImage: {
    width: '100%',
    height: 220,
  },

  cardOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
    padding: 20,
    paddingBottom: 24,
  },

  eventTitle: {
    fontFamily: Fonts.bold,
    fontSize: 22,
    color: '#fff',
    marginBottom: 8,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: {width: 0, height: 2},
    textShadowRadius: 4,
    letterSpacing: 0.3,
  },

  eventSubtitle: {
    fontFamily: Fonts.regular,
    color: '#fff',
    fontSize: 14,
    lineHeight: 20,
    textShadowColor: 'rgba(0,0,0,0.4)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 2,
    opacity: 0.95,
  },

  /** Report Icon Button */
  reportIconButton: {
    position: 'absolute',
    top: 12,
    left: 12,
    zIndex: 10,
  },
  reportIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(239, 68, 68, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#EF4444',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.6,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },

  /** Quay lại */

  backButton: {
    alignSelf: 'flex-start',
    marginBottom: 12,
    borderRadius: 24,
    overflow: 'hidden',
    shadowColor: '#007AFF',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },

  backGradient: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },

  backContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  backText: {
    color: '#fff',
    fontFamily: Fonts.medium,
    fontSize: 13,
    marginLeft: 6,
  },

  /** Section title */
  sectionTitle: {
    fontFamily: Fonts.bold,
    fontSize: 20,
    marginBottom: 12,
  },

  /** Card loại vé (Cấp 2) */
  ticketTypeCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: Colors.primary + '20',
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  ticketTypeTitle: {
    fontFamily: Fonts.bold,
    fontSize: 18,
    color: Colors.primary,
    marginBottom: 6,
  },
  ticketTypeSub: {
    fontFamily: Fonts.regular,
    color: '#6B7280',
    fontSize: 14,
  },

  /** Card vé cụ thể (Cấp 3) */
  ticketCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E3E8EF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  qrButton: {
    marginTop: 10,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOpacity: 0.25,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 6,
    elevation: 5,
  },

  /** Modal QR */
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  qrModalBox: {
    width: '80%',
    borderRadius: 20,
    paddingVertical: 30,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 10,
  },
  closeBtn: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 6,
    borderRadius: 20,
  },
  qrBox: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 18,
    marginVertical: 20,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  downloadBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginTop: 4,
  },

  /** Loading */
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },

  /** Report Button */
  reportButton: {
    marginBottom: 16,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#EF4444',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  reportButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    gap: 8,
  },
  reportButtonText: {
    color: '#fff',
    fontFamily: Fonts.bold,
    fontSize: 16,
  },

  /** Report Modal */
  reportModalBox: {
    width: '92%',
    maxWidth: 420,
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 0,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: {width: 0, height: 8},
    elevation: 15,
    overflow: 'hidden',
  },
  reportModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#FAFBFC',
  },
  reportModalTitle: {
    fontFamily: Fonts.bold,
    fontSize: 22,
    color: Colors.textPrimary,
    letterSpacing: 0.2,
  },
  reportModalContent: {
    padding: 24,
  },
  reportLabel: {
    fontFamily: Fonts.semiBold,
    fontSize: 15,
    marginBottom: 12,
    color: Colors.textPrimary,
    letterSpacing: 0.2,
  },
  reportTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
  },
  reportTypeButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: Colors.white,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  reportTypeButtonActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  reportTypeText: {
    fontFamily: Fonts.medium,
    fontSize: 13,
    letterSpacing: 0.1,
  },
  reportReasonInput: {
    borderWidth: 1.5,
    borderColor: '#E8EAED',
    borderRadius: 14,
    padding: 14,
    minHeight: 110,
    fontFamily: Fonts.regular,
    fontSize: 15,
    color: Colors.textPrimary,
    backgroundColor: '#F8F9FA',
    marginBottom: 24,
    textAlignVertical: 'top',
  },
  reportModalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  reportCancelButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  reportSubmitButton: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 14,
    backgroundColor: '#EF4444',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#EF4444',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  reportSubmitButtonDisabled: {
    opacity: 0.6,
    shadowOpacity: 0.1,
    elevation: 2,
  },

  /** Report Button Small (cho mỗi event card) */
  reportButtonSmall: {
    borderRadius: 8,
    overflow: 'hidden',
    shadowColor: '#EF4444',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  reportButtonGradientSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    gap: 6,
  },
  reportButtonTextSmall: {
    color: '#fff',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
  },

  /** Empty Container */
  emptyContainer: {
    paddingVertical: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },

  /** Event Detail Modal */
  eventDetailModalBox: {
    backgroundColor: '#fff',
    borderRadius: 28,
    width: '96%',
    maxHeight: '92%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
    overflow: 'hidden',
  },
  eventDetailModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    backgroundColor: '#FAFBFC',
  },
  eventDetailModalTitle: {
    flex: 1,
    marginRight: 16,
    fontFamily: Fonts.bold,
    fontSize: 22,
    color: Colors.textPrimary,
    letterSpacing: 0.2,
  },
  eventDetailModalContent: {
    padding: 24,
    maxHeight: '75%',
  },
  eventDetailInfo: {
    marginBottom: 24,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E8EAED',
  },
  eventDetailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  eventDetailLabel: {
    fontFamily: Fonts.semiBold,
    fontSize: 15,
    marginBottom: 6,
    color: Colors.textPrimary,
    letterSpacing: 0.2,
  },
  eventDetailValue: {
    fontFamily: Fonts.regular,
    fontSize: 15,
    color: Colors.textSecondary,
    lineHeight: 22,
    marginBottom: 4,
  },

  /** View Reports Button */
  viewReportsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: '#fff',
    marginBottom: 24,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  viewReportsButtonActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 5,
  },

  /** Reports Section */
  reportsSection: {
    marginTop: 12,
    marginBottom: 24,
  },
  reportsSectionTitle: {
    fontFamily: Fonts.bold,
    fontSize: 20,
    marginBottom: 20,
    color: '#EF4444',
    letterSpacing: 0.3,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#FEE2E2',
  },
  reportsLoadingContainer: {
    paddingVertical: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportsEmptyContainer: {
    paddingVertical: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    paddingHorizontal: 20,
    marginTop: 8,
  },

  /** Report Item */
  reportItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#E8EAED',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  reportItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  reportTypeBadge: {
    backgroundColor: '#EF4444',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 20,
    shadowColor: '#EF4444',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  reportItemLabel: {
    fontFamily: Fonts.semiBold,
    fontSize: 14,
    marginTop: 12,
    marginBottom: 6,
    color: Colors.textPrimary,
    letterSpacing: 0.2,
  },
  reportItemReason: {
    fontFamily: Fonts.regular,
    fontSize: 15,
    color: Colors.textSecondary,
    lineHeight: 22,
    marginBottom: 12,
    backgroundColor: '#F8F9FA',
    padding: 12,
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: Colors.primary,
  },
  reportItemLink: {
    fontFamily: Fonts.regular,
    fontSize: 14,
    color: '#2563EB',
    textDecorationLine: 'underline',
    marginBottom: 12,
    padding: 8,
    backgroundColor: '#EFF6FF',
    borderRadius: 8,
  },
  reportReplyContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: '#E8EAED',
    backgroundColor: '#FAFBFC',
    borderRadius: 12,
    padding: 16,
    marginTop: 16,
  },
  reportItemReply: {
    fontFamily: Fonts.regular,
    fontSize: 15,
    color: Colors.textSecondary,
    lineHeight: 22,
    backgroundColor: '#F0F9FF',
    padding: 14,
    borderRadius: 12,
    marginTop: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#10B981',
  },
  reportItemNoReply: {
    fontFamily: Fonts.regular,
    fontSize: 14,
    fontStyle: 'italic',
    marginTop: 10,
    color: Colors.textLight,
    textAlign: 'center',
    paddingVertical: 8,
  },

  /** Report Button in Detail */
  reportButtonInDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    backgroundColor: '#EF4444',
    marginTop: 24,
    marginBottom: 12,
    shadowColor: '#EF4444',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
});
