import {StyleSheet, Dimensions} from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255, 255, 255, 0.35)',
  },
  container: {
    flex: 1,
  },
  contentContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  formContainer: {
    backgroundColor: Colors.white,
    paddingHorizontal: 28,
    paddingTop: 30,
    paddingBottom: 25,
    borderRadius: 28,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 12},
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 12,
    position: 'relative',
  },
  brandBadge: {
    position: 'absolute',
    width: 140,
    height: 140,
    borderBottomRightRadius: 50,
    borderTopLeftRadius: 28,
    backgroundColor: Colors.primary,
    opacity: 0.08,
    top: -30,
    left: -25,
  },
  logoWrapper: {
    alignItems: 'center',
    marginBottom: 15,
    marginTop: -5,
  },
  logo: {
    width: 200,
    height: 150,
    marginTop: 20,
    marginBottom: 20,
  },
  headerTitle: {
    color: Colors.textSecondary,
    fontSize: 28,
    fontFamily: Fonts.light,
    fontStyle: 'italic',
    letterSpacing: 0.5,
    textAlign: 'center',
    textTransform: 'none',
    marginBottom: 2,
    textShadowColor: 'rgba(0,0,0,0.08)',
    textShadowOffset: {width: 0, height: 2},
    textShadowRadius: 4,
  },
  inputContainer: {
    marginBottom: 15,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 18,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E8ECF0',
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  inputIcon: {
    width: 22,
    height: 22,
    marginRight: 12,
    tintColor: Colors.textSecondary,
    opacity: 0.6,
  },
  input: {
    flex: 1,
    paddingVertical: 18,
    fontSize: 15,
    fontFamily: Fonts.regular,
    color: Colors.textPrimary,
  },
  passwordInput: {
    paddingRight: 50, // Space for eye icon
  },
  eyeIcon: {
    position: 'absolute',
    right: 15,
    height: '100%',
    justifyContent: 'center',
  },
  passwordRequirements: {
    marginTop: 8,
    marginBottom: 16,
    paddingHorizontal: 10,
  },
  requirementText: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
    fontFamily: Fonts.regular,
  },
  requirementMet: {
    color: '#4CAF50',
    fontWeight: 'bold',
  },
  registerButton: {
    backgroundColor: Colors.primary,
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
    marginBottom: 15,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  registerButtonDisabled: {
    opacity: 0.5,
  },
  registerButtonText: {
    color: Colors.white,
    fontSize: 18,
    fontFamily: Fonts.bold,
    letterSpacing: 1.2,
  },
  loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    marginBottom: 20,
  },
  loginText: {
    color: Colors.textSecondary,
    fontSize: 14,
    fontFamily: Fonts.regular,
  },
  loginLink: {
    color: Colors.primary,
    fontSize: 14,
    fontFamily: Fonts.bold,
    textDecorationLine: 'underline',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  divider: {
    flex: 1,
    height: 1.5,
    backgroundColor: '#E8ECF0',
  },
  dividerText: {
    marginHorizontal: 16,
    color: Colors.textSecondary,
    fontSize: 13,
    fontFamily: Fonts.medium,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  socialButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E8ECF0',
    borderRadius: 18,
    paddingVertical: 16,
    width: '48%',
    backgroundColor: '#FAFBFC',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  socialIcon: {
    width: 24,
    height: 24,
    marginRight: 10,
  },
  socialText: {
    color: Colors.textPrimary,
    fontSize: 14,
    fontFamily: Fonts.semiBold,
  },
  // Select button (dropdown)
  selectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F8F9FA',
    borderRadius: 18,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E8ECF0',
    paddingHorizontal: 18,
    paddingVertical: 18,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  selectButtonText: {
    fontSize: 15,
    fontFamily: Fonts.regular,
    color: Colors.textPrimary,
    flex: 1,
  },
  selectButtonArrow: {
    fontSize: 12,
    color: Colors.textSecondary,
    marginLeft: 10,
  },
  // Dropdown
  dropdownWrapper: {
    position: 'relative',
    marginBottom: 12,
    zIndex: 10,
  },
  // Đảm bảo dropdown đầu tiên có z-index cao hơn để hiển thị trên cùng
  dropdownWrapperFirst: {
    position: 'relative',
    marginBottom: 12,
    zIndex: 20,
  },
  dropdownContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: Colors.white,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#E8ECF0',
    marginTop: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
    zIndex: 1000,
    maxHeight: 200,
  },
  dropdownItem: {
    paddingVertical: 14,
    paddingHorizontal: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  dropdownItemSelected: {
    backgroundColor: '#E3F2FD',
  },
  dropdownItemText: {
    fontSize: 15,
    fontFamily: Fonts.regular,
    color: Colors.textPrimary,
  },
  dropdownItemTextSelected: {
    fontFamily: Fonts.bold,
    color: Colors.primary,
  },
  // Section title
  sectionTitle: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: Colors.textPrimary,
    marginBottom: 12,
    marginTop: 8,
  },
  // Notification settings
  notificationContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: 18,
    padding: 16,
    marginTop: 8,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E8ECF0',
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E8ECF0',
  },
  switchLabel: {
    fontSize: 15,
    fontFamily: Fonts.regular,
    color: Colors.textPrimary,
    flex: 1,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    width: '100%',
    maxWidth: 400,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E8ECF0',
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: Fonts.bold,
    color: Colors.textPrimary,
    flex: 1,
  },
  modalCloseButton: {
    padding: 5,
  },
  modalCloseText: {
    fontSize: 24,
    color: Colors.textSecondary,
    fontWeight: 'bold',
  },
  modalScrollView: {
    maxHeight: 400,
    padding: 16,
  },
  modalConfirmButton: {
    backgroundColor: Colors.primary,
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: 'center',
    margin: 16,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  modalConfirmText: {
    color: Colors.white,
    fontSize: 16,
    fontFamily: Fonts.bold,
  },
  // Chips (multi-select)
  chipsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#F0F0F0',
    borderWidth: 2,
    borderColor: '#E8ECF0',
    marginRight: 10,
    marginBottom: 10,
  },
  chipSelected: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  chipText: {
    fontSize: 14,
    fontFamily: Fonts.regular,
    color: Colors.textPrimary,
  },
  chipTextSelected: {
    color: Colors.white,
    fontFamily: Fonts.bold,
  },
});

export {styles};
