import {StyleSheet, Dimensions, Platform} from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    padding: 24,
  },

  // Modern Hero Image Section
  imageContainer: {
    width: '100%',
    height: height * 0.42,
    position: 'relative',
  },
  eventImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  imageOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  
  // Modern Back Button with glassmorphism
  backButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 44,
    left: 20,
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  backIcon: {
    width: 22,
    height: 22,
    tintColor: '#1E293B',
  },
  qrButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 54 : 44,
    right: 20,
    zIndex: 10,
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  qrIcon: {
    width: 22,
    height: 22,
    tintColor: Colors.primary,
  },

  // Modern Content Card with floating effect
  content: {
    padding: 24,
    backgroundColor: Colors.white,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -36,
    minHeight: height * 0.65,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -12},
    shadowOpacity: 0.08,
    shadowRadius: 24,
    elevation: 16,
  },

  // Modern Title Section
  titleSection: {
    marginBottom: 20,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF9C3',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  starIcon: {
    width: 16,
    height: 16,
    marginRight: 6,
    tintColor: '#F59E0B',
  },

  // Modern Price Badge with gradient effect
  priceBadge: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 24,
    marginBottom: 24,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 8,
  },

  // Modern Stats Section with cards
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 28,
    gap: 12,
  },
  statBox: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    paddingVertical: 18,
    paddingHorizontal: 12,
    borderRadius: 20,
  },
  statValue: {
    fontSize: Fonts.xl,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    marginBottom: 6,
    color: Colors.primary,
  },
  statLabel: {
    fontSize: Fonts.xs,
    color: '#64748B',
    fontFamily: Fonts.medium,
    textAlign: 'center',
  },

  // Modern Organizer Section
  organizerSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  organizerAvatar: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  organizerAvatarText: {
    fontSize: Fonts.lg,
    fontWeight: '700',
    fontFamily: Fonts.bold,
  },
  organizerInfo: {
    flex: 1,
  },
  organizerName: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    marginBottom: 4,
    color: '#1E293B',
  },
  organizerEvents: {
    fontSize: Fonts.sm,
    color: '#64748B',
    fontFamily: Fonts.regular,
  },

  // Modern Tags Section
  tagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 28,
    gap: 10,
  },
  tag: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  tagText: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.semiBold,
    color: Colors.primary,
  },

  // Modern Program Section
  programSection: {
    marginBottom: 28,
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  sectionTitle: {
    fontSize: Fonts.xl,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    marginBottom: 20,
    color: '#1E293B',
  },
  programItem: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  programTime: {
    width: 64,
    height: 64,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 4,
  },
  programTimeText: {
    fontSize: Fonts.sm,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: Colors.white,
  },
  programContent: {
    flex: 1,
    justifyContent: 'center',
  },
  programTitle: {
    fontSize: Fonts.md,
    fontWeight: '600',
    fontFamily: Fonts.semiBold,
    marginBottom: 6,
    color: '#1E293B',
  },
  programDescription: {
    fontSize: Fonts.sm,
    color: '#64748B',
    fontFamily: Fonts.regular,
    lineHeight: 20,
  },

  // Modern Benefits Section
  benefitsSection: {
    marginBottom: 28,
    backgroundColor: '#F0FDF4',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  benefitsTitle: {
    fontSize: Fonts.xl,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    marginBottom: 20,
    color: '#166534',
  },
  benefitItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  benefitIcon: {
    width: 22,
    height: 22,
    marginRight: 14,
    tintColor: '#22C55E',
  },
  benefitText: {
    fontSize: Fonts.md,
    fontFamily: Fonts.regular,
    flex: 1,
    color: '#166534',
  },

  // Modern Details Section
  detailsSection: {
    marginBottom: 28,
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 18,
    paddingBottom: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  detailIcon: {
    width: 22,
    height: 22,
    marginRight: 14,
    tintColor: Colors.primary,
    marginTop: 2,
  },
  detailInfo: {
    flex: 1,
  },

  // Modern Ticket Section
  ticketRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 18,
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
    marginBottom: 14,
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
  },
  ticketRowUnavailable: {
    opacity: 0.5,
    backgroundColor: '#F1F5F9',
  },
  ticketInfo: {
    flex: 1,
  },
  ticketName: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    marginBottom: 6,
    color: '#1E293B',
  },
  ticketDescription: {
    fontSize: Fonts.sm,
    color: '#64748B',
    fontFamily: Fonts.regular,
    marginBottom: 10,
  },
  ticketStats: {
    flexDirection: 'row',
    gap: 16,
  },
  ticketStat: {
    fontSize: Fonts.xs,
    color: '#94A3B8',
    fontFamily: Fonts.medium,
  },
  ticketPriceContainer: {
    alignItems: 'flex-end',
    backgroundColor: Colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
  },
  ticketPrice: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: Colors.white,
  },

  // Modern Description Section
  descriptionSection: {
    marginBottom: 32,
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },

  // Modern Related Events Section
  relatedEventsSection: {
    marginBottom: 28,
  },
  relatedEventCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderRadius: 18,
    padding: 14,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  relatedEventImage: {
    width: 72,
    height: 72,
    borderRadius: 14,
    marginRight: 14,
  },
  relatedEventInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  relatedEventTitle: {
    fontSize: Fonts.md,
    fontWeight: '600',
    fontFamily: Fonts.semiBold,
    marginBottom: 6,
    color: '#1E293B',
  },
  relatedEventDate: {
    fontSize: Fonts.sm,
    color: '#64748B',
    fontFamily: Fonts.regular,
    marginBottom: 6,
  },
  relatedEventPrice: {
    fontSize: Fonts.sm,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: Colors.primary,
  },

  // Modern Share Button
  shareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 18,
    marginBottom: 20,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 8,
  },
  shareButtonDisabled: {
    backgroundColor: '#94A3B8',
    shadowColor: '#94A3B8',
    shadowOpacity: 0.2,
  },
  shareButtonText: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    marginLeft: 10,
  },

  // Modern Actions Section
  actionsSection: {
    marginBottom: 28,
  },
  joinButton: {
    marginBottom: 18,
    borderRadius: 20,
    paddingVertical: 20,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  secondaryActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  actionButton: {
    flex: 1,
  },

  // Modern Share Modal
  shareOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  shareBackdrop: {
    flex: 1,
  },
  shareContainer: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 40,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 16,
  },
  shareHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  closeIcon: {
    width: 24,
    height: 24,
    tintColor: '#64748B',
  },
  shareGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  shareGridItem: {
    width: '30%',
    marginBottom: 24,
    alignItems: 'center',
  },
  shareGridIcon: {
    width: 56,
    height: 56,
    marginBottom: 10,
    borderRadius: 16,
  },
  shareGridText: {
    textAlign: 'center',
    fontSize: Fonts.sm,
    fontFamily: Fonts.medium,
    color: '#64748B',
  },

  // Modern Invite Friends Modal
  inviteModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  inviteModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  inviteModalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '90%',
    paddingBottom: 24,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -8},
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 20,
  },
  inviteModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  inviteModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: '#1E293B',
  },
  inviteModalCloseButton: {
    padding: 6,
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
  },
  inviteModalCloseIcon: {
    width: 20,
    height: 20,
    tintColor: '#64748B',
  },
  inviteModalBody: {
    maxHeight: height * 0.55,
    padding: 24,
  },
  inviteMessageContainer: {
    marginBottom: 28,
  },
  inviteMessageLabel: {
    fontSize: Fonts.md,
    fontWeight: '600',
    marginBottom: 12,
    fontFamily: Fonts.semiBold,
    color: '#1E293B',
  },
  inviteMessageInput: {
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: 16,
    padding: 16,
    fontSize: Fonts.md,
    fontFamily: Fonts.regular,
    color: '#1E293B',
    minHeight: 100,
    textAlignVertical: 'top',
    backgroundColor: '#F8FAFC',
  },
  friendsListContainer: {
    marginBottom: 20,
  },
  friendsListTitle: {
    fontSize: Fonts.md,
    fontWeight: '600',
    marginBottom: 18,
    fontFamily: Fonts.semiBold,
    color: '#1E293B',
  },
  loadingFriendsContainer: {
    padding: 48,
    alignItems: 'center',
  },
  emptyFriendsContainer: {
    padding: 48,
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderRadius: 16,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 14,
    marginBottom: 12,
    borderRadius: 16,
    backgroundColor: '#F8FAFC',
    borderWidth: 2,
    borderColor: 'transparent',
  },
  friendItemSelected: {
    backgroundColor: '#EFF6FF',
    borderColor: Colors.primary,
  },
  friendItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  friendAvatar: {
    width: 52,
    height: 52,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 14,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  friendAvatarImage: {
    width: 52,
    height: 52,
    borderRadius: 16,
  },
  friendAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.white,
  },
  friendInfo: {
    flex: 1,
  },
  friendName: {
    fontSize: Fonts.md,
    fontWeight: '600',
    fontFamily: Fonts.semiBold,
    marginBottom: 4,
    color: '#1E293B',
  },
  friendDistrict: {
    fontSize: Fonts.sm,
    color: '#64748B',
  },
  friendCheckmark: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  inviteModalFooter: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    gap: 14,
  },
  inviteModalButton: {
    flex: 1,
  },
  inviteModalCancelButton: {
    marginRight: 0,
  },
  inviteModalSendButton: {
    marginLeft: 0,
  },
});

export default styles;
