import { StyleSheet, Dimensions, Platform } from 'react-native';
import Colors from '../../constants/Colors';
import Fonts from '../../constants/Fonts';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F7FA',
  },
  
  // Header with Gradient Effect
  header: {
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'ios' ? 60 : 50,
    paddingBottom: 24,
    backgroundColor: Colors.white,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
  },
  
  // Modern Search with Icon Animation
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.white,
    marginHorizontal: 20,
    marginTop: 20,
    marginBottom: 16,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#F0F3F7',
  },
  searchIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.primary,
    marginRight: 12,
  },
  searchInput: {
    flex: 1,
    fontSize: Fonts.md,
    fontFamily: Fonts.medium,
    color: Colors.textPrimary,
    paddingVertical: 0,
  },
  
  // Premium Stats Cards with Gradient
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 20,
    marginBottom: 12,
    gap: 10,
  },
  
  statsHint: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.regular,
    color: Colors.textLight,
    paddingHorizontal: 20,
    marginBottom: 20,
    fontStyle: 'italic',
  },
  statCard: {
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 20,
    alignItems: 'center',
    flex: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 0,
    position: 'relative',
    overflow: 'hidden',
  },
  
  // Modern View Mode Tabs
  viewModeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  viewModeTabs: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#F0F3F7',
  },
  viewModeTab: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 12,
    minWidth: 80,
    alignItems: 'center',
    transition: 'all 0.3s ease',
  },
  activeViewModeTab: {
    backgroundColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  navigationButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  navButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 2,
    borderColor: '#F0F3F7',
  },
  
  // Content
  content: {
    flex: 1,
  },
  
  // Loading with Modern Animation
  loadingContainer: {
    paddingVertical: 60,
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontFamily: Fonts.medium,
  },
  
  // Premium Calendar Design
  calendarContainer: {
    backgroundColor: Colors.white,
    marginHorizontal: 20,
    marginBottom: 30,
    borderRadius: 28,
    padding: 20,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#F0F3F7',
  },
  calendarMonthHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#F0F3F7',
  },
  calendarMonthYearText: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    color: Colors.textPrimary,
    letterSpacing: 0.5,
  },
  todayButton: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 16,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  calendarHeader: {
    flexDirection: 'row',
    borderBottomWidth: 2,
    borderBottomColor: '#F0F3F7',
    paddingBottom: 16,
    marginBottom: 16,
  },
  calendarHeaderDay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarHeaderText: {
    fontWeight: '700',
    fontSize: Fonts.sm,
    color: Colors.textSecondary,
    letterSpacing: 1,
    fontFamily: Fonts.bold,
  },
  calendarGrid: {
    width: '100%',
  },
  calendarWeek: {
    flexDirection: 'row',
    width: '100%',
    marginBottom: 6,
  },
  calendarDay: {
    flex: 1,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    margin: 3,
    backgroundColor: '#FAFBFC',
    position: 'relative',
    borderWidth: 2,
    borderColor: 'transparent',
    transition: 'all 0.3s ease',
  },
  calendarDayOtherMonth: {
    opacity: 0.3,
    backgroundColor: '#F8F9FA',
  },
  calendarDayToday: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    transform: [{ scale: 1.05 }],
  },
  calendarDaySelected: {
    backgroundColor: '#E8F4FD',
    borderColor: Colors.primary,
    borderWidth: 3,
  },
  calendarDayWithEvents: {
    borderWidth: 2.5,
    borderColor: Colors.primary,
    backgroundColor: '#E3F2FD',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  calendarDayNumber: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
  },
  pushpinIcon: {
    position: 'absolute',
    top: -20,
    right: -18,
    width: 40,
    height: 40,
    zIndex: 10,
  },
  eventIndicator: {
    position: 'absolute',
    bottom: 6,
    alignItems: 'center',
    flexDirection: 'row',
    gap: 3,
  },
  eventDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.primary,
  },
  selectedDateContainer: {
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 2,
    borderTopColor: '#F0F3F7',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    borderRadius: 16,
    paddingVertical: 16,
    marginHorizontal: -4,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  selectedDateText: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: Colors.white,
    letterSpacing: 0.5,
  },
  
  // Premium Week View
  weekDayColumn: {
    flex: 1,
    borderRightWidth: 1.5,
    borderRightColor: '#E8EDF2',
    minHeight: 160,
    backgroundColor: Colors.white,
  },
  weekDayHeader: {
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#F0F3F7',
    backgroundColor: '#FAFBFC',
  },
  weekDayNumber: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 8,
    position: 'relative',
    borderWidth: 2.5,
    borderColor: 'transparent',
  },
  pushpinIconWeek: {
    position: 'absolute',
    top: -22,
    right: -18,
    width: 38,
    height: 38,
    zIndex: 10,
  },
  weekDayNumberToday: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    transform: [{ scale: 1.1 }],
  },
  weekDayNumberSelected: {
    backgroundColor: '#E8F4FD',
    borderColor: Colors.primary,
  },
  weekDayDate: {
    marginTop: 6,
    fontSize: Fonts.xs,
    color: Colors.textLight,
    fontFamily: Fonts.medium,
  },
  weekDayEvents: {
    flex: 1,
    padding: 12,
    backgroundColor: Colors.white,
  },
  weekDayEventsContent: {
    flexGrow: 1,
    paddingBottom: 16,
  },
  weekEventsIconsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 16,
  },
  weekEventIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E3F2FD',
    borderWidth: 2.5,
    borderColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  weekEventIconImage: {
    width: 24,
    height: 24,
    tintColor: Colors.primary,
  },
  
  // Premium Day View
  dayViewContainer: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  dayCard: {
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    backgroundColor: '#667eea',
    borderRadius: 32,
    padding: 28,
    marginBottom: 28,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  dayCardHeader: {
    marginBottom: 20,
    alignItems: 'center',
  },
  monthYearText: {
    fontSize: Fonts.xl,
    fontWeight: '700',
    textAlign: 'center',
    color: Colors.white,
    opacity: 0.95,
    fontFamily: Fonts.bold,
    letterSpacing: 1,
  },
  dayCardMain: {
    alignItems: 'center',
    marginVertical: 28,
  },
  dayNumberText: {
    fontSize: 110,
    fontWeight: '900',
    color: Colors.white,
    lineHeight: 120,
    fontFamily: Fonts.extraBold,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 4 },
    textShadowRadius: 12,
    letterSpacing: -2,
  },
  dayNameText: {
    fontSize: 26,
    fontWeight: '800',
    marginTop: 16,
    letterSpacing: 3,
    color: Colors.white,
    fontFamily: Fonts.bold,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  dayInfoTable: {
    marginTop: 28,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 20,
    padding: 20,
    backdropFilter: 'blur(20px)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  dayInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  dayInfoCell: {
    alignItems: 'center',
    flex: 1,
  },
  dayInfoLabel: {
    fontSize: Fonts.sm,
    marginBottom: 8,
    fontWeight: '600',
    color: Colors.white,
    opacity: 0.9,
    fontFamily: Fonts.semiBold,
    letterSpacing: 0.5,
  },
  dayInfoValue: {
    fontSize: 20,
    fontWeight: '900',
    color: Colors.white,
    fontFamily: Fonts.extraBold,
  },
  emptyDayContainer: {
    paddingVertical: 80,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 24,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  dayEventsList: {
    marginBottom: 28,
  },
  eventsTitle: {
    marginBottom: 20,
    fontWeight: '800',
    fontSize: 24,
    fontFamily: Fonts.extraBold,
    color: Colors.textPrimary,
    letterSpacing: 0.5,
  },
  dayEventCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F0F3F7',
  },
  dayEventIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 18,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  dayEventContent: {
    flex: 1,
    justifyContent: 'center',
  },
  
  // Events List Section
  eventsListSection: {
    marginBottom: 24,
  },
  eventCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 24,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F0F3F7',
  },
  eventCardIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 18,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  eventCardContent: {
    flex: 1,
    justifyContent: 'center',
  },
  emptyEventsContainer: {
    paddingVertical: 80,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 24,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  
  // Premium Modal Design
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    maxHeight: '94%',
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 28,
    paddingBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#F0F3F7',
  },
  modalBody: {
    maxHeight: Dimensions.get('window').height * 0.72,
  },
  eventDetailSection: {
    marginBottom: 28,
    padding: 22,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8EDF2',
  },
  eventInfoSection: {
    marginBottom: 28,
    padding: 22,
    backgroundColor: '#FAFBFC',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E8EDF2',
  },
  eventInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
    flexWrap: 'wrap',
    paddingVertical: 12,
    paddingHorizontal: 4,
    borderBottomWidth: 1.5,
    borderBottomColor: '#F0F3F7',
    minHeight: 44,
  },
  ticketsSection: {
    marginBottom: 28,
  },
  ticketsTitle: {
    marginBottom: 20,
    fontSize: 24,
    fontFamily: Fonts.extraBold,
    fontWeight: '800',
  },
  ticketsList: {
    marginTop: 16,
  },
  ticketGroup: {
    marginBottom: 24,
    padding: 22,
    backgroundColor: '#F8F9FA',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E8EDF2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
  },
  ticketGroupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
    paddingBottom: 18,
    borderBottomWidth: 2,
    borderBottomColor: '#E8EDF2',
  },
  ticketItem: {
    marginBottom: 20,
    padding: 20,
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: '#E8EDF2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  ticketInfo: {
    marginBottom: 16,
  },
  qrButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    minHeight: 48,
  },
  qrContainer: {
    marginTop: 20,
    alignItems: 'center',
    padding: 24,
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E8EDF2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },
  qrImage: {
    width: 240,
    height: 240,
  },
});

const enhancedStyles = StyleSheet.create({
  // ==================== ENHANCED EVENT CARD ====================
  dayEventCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: 0,
    borderRadius: 28,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 0,
    overflow: 'hidden',
  },
  
  dayEventIconContainer: {
    width: 100,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  
  dayEventIconGradient: {
    position: 'absolute',
    top: -20,
    right: -20,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  
  dayEventIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0,
  },
  
  dayEventContent: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
  
  eventTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 16,
    flexWrap: 'wrap',
    gap: 8,
  },
  
  eventTitle: {
    fontSize: Fonts.xl,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    flex: 1,
    minWidth: '60%',
    letterSpacing: 0.3,
    lineHeight: 28,
  },
  
  eventStatusBadge: {
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 14,
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  
  eventStatusText: {
    fontSize: Fonts.xs,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    letterSpacing: 0.5,
  },
  
  eventInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F8F9FA',
    borderRadius: 14,
  },
  
  eventInfoIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'visible',
  },
  
  eventInfoText: {
    fontSize: Fonts.md,
    fontFamily: Fonts.medium,
    color: '#424242',
    flex: 1,
    lineHeight: 22,
  },
  // ==================== ENHANCED MODAL DESIGN ====================
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'flex-end',
  },
  
  modalContent: {
    backgroundColor: '#F5F7FA',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    maxHeight: '94%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -12 },
    shadowOpacity: 0.3,
    shadowRadius: 32,
    elevation: 20,
    overflow: 'hidden',
  },
  
  modalHeaderGradient: {
    backgroundColor: Colors.white,
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 24,
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
  },
  
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  
  modalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 16,
  },
  
  modalHeaderIconBadge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  
  modalTitle: {
    fontSize: 24,
    fontWeight: '900',
    fontFamily: Fonts.extraBold,
    color: '#1A1A2E',
    flex: 1,
    letterSpacing: 0.3,
    lineHeight: 32,
  },
  
  eventDetailTabs: {
    flexDirection: 'row',
    marginTop: 20,
    backgroundColor: '#F0F3F7',
    borderRadius: 16,
    padding: 4,
    gap: 4,
  },
  
  eventDetailTab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  
  eventDetailTabActive: {
    backgroundColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  
  eventDetailTabText: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    letterSpacing: 0.3,
  },
  
  modalCloseButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F0F3F7',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  
  modalBody: {
    maxHeight: Dimensions.get('window').height * 0.72,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  // ==================== EVENT DETAIL SECTIONS ====================
  eventDetailHero: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F0F4F8',
  },
  
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  
  sectionIconBadge: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    backgroundColor: Colors.primary,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    letterSpacing: 0.3,
    flex: 1,
  },
  
  descriptionText: {
    fontSize: Fonts.md,
    lineHeight: 26,
    fontFamily: Fonts.regular,
    color: '#616161',
    letterSpacing: 0.2,
  },
  
  eventInfoSection: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#F0F4F8',
  },
  
  infoSectionTitle: {
    marginBottom: 20,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#F0F4F8',
  },
  
  infoSectionTitleText: {
    fontSize: 20,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    letterSpacing: 0.3,
  },
  
  infoDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 0,
    marginBottom: 16,
    backgroundColor: '#FAFBFC',
    borderRadius: 16,
    paddingLeft: 16,
    paddingRight: 16,
    borderWidth: 1,
    borderColor: '#E8EDF2',
  },
  
  infoDetailLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  
  infoDetailIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    backgroundColor: '#E3F2FD',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  
  locationRowCustom: {
    marginBottom: 16,
    backgroundColor: '#FAFBFC',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E8EDF2',
    borderLeftWidth: 0,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  
  locationLabelCustom: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.semiBold,
    color: '#757575',
    letterSpacing: 0.3,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  
  locationValueCustom: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  
  infoDetailContent: {
    flex: 1,
  },
  
  infoDetailLabel: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.semiBold,
    color: '#757575',
    letterSpacing: 0.3,
    marginBottom: 4,
    textTransform: 'uppercase',
  },
  
  infoDetailValue: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    letterSpacing: 0.2,
    lineHeight: 22,
  },
  
  mapButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#E3F2FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    borderWidth: 1,
    borderColor: '#BBDEFB',
  },
  
  googleCalendarButtonContainer: {
    marginTop: 8,
    paddingTop: 20,
    borderTopWidth: 2,
    borderTopColor: '#F0F4F8',
  },
  
  googleCalendarButton: {
    marginTop: 0,
  },
  
  // ==================== TICKETS SECTION ====================
  ticketsSection: {
    marginBottom: 28,
  },
  
  ticketsSectionHeader: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    padding: 24,
    marginBottom: 20,
    shadowColor: '#2196F3',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 6,
  },
  
  ticketsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  
  ticketsList: {
    marginTop: 0,
  },
  
  ticketGroup: {
    marginBottom: 16,
    backgroundColor: Colors.white,
    borderRadius: 20,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#F0F3F7',
  },
  
  ticketGroupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 2,
    borderBottomColor: '#F0F3F7',
  },
  
  ticketGroupHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  
  expandIcon: {
    fontSize: 16,
    color: Colors.textSecondary,
    fontWeight: '700',
  },
  
  ticketGroupTitle: {
    fontSize: Fonts.lg,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    flex: 1,
    letterSpacing: 0.3,
    marginRight: 12,
  },
  
  ticketCountBadge: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  
  ticketItem: {
    marginBottom: 12,
    backgroundColor: Colors.white,
    borderRadius: 16,
    padding: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#F0F3F7',
  },
  
  ticketItemCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  
  ticketItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  
  ticketStatusIndicator: {
    width: 4,
    height: 40,
    borderRadius: 2,
    marginRight: 12,
  },
  
  ticketItemInfo: {
    flex: 1,
  },
  
  ticketCodeCompact: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  
  ticketTypeCompact: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.regular,
    color: '#757575',
    letterSpacing: 0.2,
  },
  
  ticketItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  
  ticketStatusBadgeCompact: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    minWidth: 70,
    alignItems: 'center',
    marginRight: 8,
  },
  
  ticketStatusTextCompact: {
    fontSize: Fonts.xs,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    letterSpacing: 0.3,
  },
  
  qrButtonCompact: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F0F3F7',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E8EDF2',
  },
  
  qrContainerCompact: {
    paddingTop: 12,
    paddingBottom: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8F9FA',
    borderTopWidth: 1,
    borderTopColor: '#F0F3F7',
    alignItems: 'center',
  },
  
  qrImageWrapperCompact: {
    backgroundColor: Colors.white,
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  
  qrImageCompact: {
    width: 180,
    height: 180,
    borderRadius: 8,
  },
  
  qrHelperTextCompact: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.regular,
    color: '#757575',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  
  showMoreButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#E8EDF2',
    borderStyle: 'dashed',
  },
  
  showMoreText: {
    fontSize: Fonts.sm,
    fontWeight: '600',
    fontFamily: Fonts.semiBold,
    letterSpacing: 0.3,
  },
  
  loadMoreButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  
  loadMoreText: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    letterSpacing: 0.5,
  },
  
  ticketItemHeader: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  
  ticketItemHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  
  ticketItemIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  
  ticketItemCodeContainer: {
    flex: 1,
  },
  
  ticketItemCodeLabel: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.regular,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  
  ticketItemCode: {
    fontSize: Fonts.lg,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    color: Colors.white,
    letterSpacing: 1,
  },
  
  ticketItemBody: {
    padding: 20,
  },
  
  ticketInfoGrid: {
    marginBottom: 20,
  },
  
  ticketInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    borderLeftWidth: 4,
    borderLeftColor: Colors.primary,
  },
  
  ticketInfoIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E3F2FD',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  
  ticketInfoContent: {
    flex: 1,
  },
  
  ticketLabel: {
    fontSize: Fonts.xs,
    fontWeight: '600',
    fontFamily: Fonts.semiBold,
    color: '#757575',
    marginBottom: 4,
    letterSpacing: 0.3,
  },
  
  ticketValue: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: '#1A1A2E',
    letterSpacing: 0.2,
  },
  
  ticketStatusBadge: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    shadowColor: '#4CAF50',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  
  qrButton: {
    backgroundColor: Colors.primary,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    minHeight: 52,
    marginBottom: 20,
  },
  
  qrButtonText: {
    fontSize: Fonts.md,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: Colors.white,
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  
  qrContainer: {
    marginTop: 0,
    alignItems: 'center',
    padding: 24,
    backgroundColor: '#F8F9FA',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E3F2FD',
    borderStyle: 'dashed',
  },
  
  qrImageWrapper: {
    backgroundColor: Colors.white,
    padding: 20,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 16,
  },
  
  qrImage: {
    width: 240,
    height: 240,
    borderRadius: 12,
  },
  
  qrLabel: {
    fontSize: Fonts.sm,
    fontWeight: '700',
    fontFamily: Fonts.bold,
    color: Colors.primary,
    marginBottom: 12,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  
  qrHelperText: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.regular,
    color: '#757575',
    textAlign: 'center',
    letterSpacing: 0.3,
    lineHeight: 18,
  },
  // ==================== EMPTY STATES ====================
  emptyEventsContainer: {
    paddingVertical: 100,
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: 28,
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 6,
  },
  
  emptyStateIcon: {
    width: 120,
    height: 120,
    tintColor: Colors.textLight,
    marginBottom: 24,
    opacity: 0.3,
  },
  
  emptyStateTitle: {
    fontSize: 22,
    fontWeight: '800',
    fontFamily: Fonts.bold,
    marginBottom: 12,
    color: '#424242',
    letterSpacing: 0.3,
  },
  
  emptyStateText: {
    fontSize: Fonts.md,
    fontFamily: Fonts.regular,
    color: '#757575',
    textAlign: 'center',
    paddingHorizontal: 40,
    lineHeight: 24,
    letterSpacing: 0.2,
  },
  // ==================== STATS MODAL ====================
  statsModalHeader: {
    backgroundColor: Colors.white,
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 24,
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
  },
  
  eventCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: 0,
    borderRadius: 28,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 0,
    overflow: 'hidden',
  },
  
  eventCardIcon: {
    width: 100,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  
  eventCardContent: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
  },
});

export { styles, enhancedStyles };