import { StyleSheet } from 'react-native';
import Colors from '../../../constants/Colors';
import Fonts from '../../../constants/Fonts';

const styles = StyleSheet.create({
  eventCard: {
    backgroundColor: Colors.white,
    borderRadius: 16,
    marginRight: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
    borderWidth: 0,
    width: 340,
    flexDirection: 'row',
    height: 130,
    overflow: 'hidden',
  },
  eventImage: {
    width: 120,
    height: 130,
    resizeMode: 'cover',
  },
  imageContainer: {
    position: 'relative',
    width: 120,
    height: 130,
    backgroundColor: '#F5F7FA',
  },
  eventInfo: {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 12,
    justifyContent: 'space-between',
  },
  eventTitle: {
    fontSize: 15,
    fontFamily: Fonts.bold,
    color: Colors.textPrimary,
    marginBottom: 6,
    lineHeight: 20,
    letterSpacing: -0.2,
  },
  eventCategory: {
    fontSize: Fonts.xs,
    fontFamily: Fonts.semibold,
    color: Colors.primary,
    backgroundColor: Colors.primary + '15',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginBottom: 8,
    overflow: 'hidden',
  },
  eventDetails: {
    marginBottom: 4,
  },
  eventDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  eventDetailText: {
    fontSize: 12,
    fontFamily: Fonts.medium,
    color: Colors.textSecondary,
    letterSpacing: -0.1,
  },
  eventFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 'auto',
  },
  priceContainer: {
    backgroundColor: Colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    shadowColor: Colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  priceText: {
    fontSize: 13,
    fontFamily: Fonts.bold,
    color: Colors.white,
    letterSpacing: 0.2,
  },
  favoriteButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  favoriteIcon: {
    width: 20,
    height: 20,
    tintColor: Colors.error,
  },
  dateBadge: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
    alignItems: 'center',
    minWidth: 50,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.05)',
  },
  dateBadgeText: {
    fontSize: 16,
    fontFamily: Fonts.bold,
    color: Colors.primary,
    textAlign: 'center',
    lineHeight: 18,
    letterSpacing: -0.3,
  },
  dateBadgeSubtext: {
    fontSize: 10,
    fontFamily: Fonts.semibold,
    color: Colors.textSecondary,
    textAlign: 'center',
    lineHeight: 12,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  aiRecommendationBadge: {
    backgroundColor: 'rgba(139, 92, 246, 1)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'rgba(139, 92, 246, 0.4)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  aiRecommendationText: {
    fontSize: 10,
    fontFamily: Fonts.bold,
    color: Colors.white,
    marginLeft: 4,
    letterSpacing: 0.5,
  },
  aiIcon: {
    width: 12,
    height: 12,
    tintColor: Colors.white,
  },
});

export { styles };